name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 3.0.0-alpha.1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: '>=0.15.0 <1.0.0'

  # Plugins for parsing css
  csslib: '>=0.17.0 <1.0.0'

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: '>=1.0.1 <2.0.0'

  # Plugins for rendering the <video> tag.
  video_player:
    git:
      url: https://github.com/JasmitSingh90/plugins.git
      ref: plugin-latest-changes
      path: packages/video_player/video_player

  chewie:
    git:
      url: https://github.com/JasmitSingh90/chewie.git
      ref: master

  # Plugin for rendering the <iframe> tag.
  webview_flutter: '>=2.0.4 <4.0.0'

  # Plugins for rendering the <audio> tag.
  chewie_audio:
    git:
      url: https://github.com/iAmPlus/chewie_audio.git
      ref: master

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^0.22.0

  # Plugin for rendering MathML
  flutter_math_fork: '>=0.4.2+1 <1.0.0'

  # plugin for firstWhereOrNull extension on lists
  collection: '>=1.15.0 <2.0.0'

  # plugin to convert integers to numerals
  numerus: '>=1.1.1 <2.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
